---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создания игровой сессии с выбором параметров задания (сложности, типа задания, времени на задание и т.д)
  - Пользователь должен иметь возможность подключения к созданной игровой сессии
  - Пользователь должен иметь возможность создания, выбора параметров турнирной игровой сессии
  - Пользователь должен иметь возможность подключения к уже созданным турнирным игровым сессиям
  - Пользователь должен иметь возможность переподключения к игровой сессии в случае вылета
  - Пользователь должен иметь возможность покинуть игровую сессию в случае необходимости
  - Пользователь должен иметь возможность проверить написанный им код в процессе игры, находясь в игровой сессии
  - Пользователь должен иметь возможность покинуть игровую сессию по завершению игры с сохраненным в статистику результатом
  - Пользователь должен иметь возможность просматривать свой профиль
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность просматривать профили других пользователей
  - Пользователь должен иметь возможность просматривать общую статистику рейтинга пользователей
  - Пользователь должен иметь возможность фильтровать общую статистику рейтинга пользователей по имени, неделям, месяцам, общему результату и т.д и т.п
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность оставаться авторизованным после перезагрузки страницы
  - Пользователь должен иметь возможность пользоваться чатом во время игровой сессии
  - Пользователь должен иметь возможность пользоваться общим чатом при нахождении на главной странице сайта
  - Пользователь должен иметь возможность писать личные сообщения другим пользователям
  - Пользователь должен иметь возможность просматривать историю личных сообщений
  - Пользователь должен иметь возможность менять язык страницы с английского на русский и наоборот
  - Пользователь должен иметь возможность смотреть за процессом уже запущенной игровой сессии
